### ISSUE TITLE
AMA

### ISSUE THREAD

**Issue by robertmt** [sindresorhus/todo#25]
mdo has an AMA repo: https://github.com/mdo/ama

maybe you should do that too

**Comment by arthurvr** [comment]
Of course Sindre should decide this but it sounds really time-consuming and I wonder how much value it adds.

**Comment by sindresorhus** [comment]
I already answer a lot of emails that could have been an AMA, so might be nice to have something public I can refer to. I'll look into this next week.

**Comment by arthurvr** [comment]
Now that I think about it me too. I answer questions so might as well just answer them in public. On the other hand we should really make sure it doesn't get a big collection of support questions...

People tend to ask a lot of support questions in issue trackers so I wonder what happens if you literally say to "ask me anything"...

**Comment by arthurvr** [comment]
https://github.com/sindresorhus/ama :smiley:

**Comment by matiassingers** [comment]
:+1:
